namespace com.advantech.nfc
{
	public enum EinkImageTemplate
	{
		EINK_IMAGE_BLACK,
		EINK_IMAGE_WHITE,
		EINK_IMAGE_VERTICAL_0,
		EINK_IMAGE_VERTICAL_1,
		EINK_IMAGE_HORIZOTAL_0,
		EINK_IMAGE_HORIZOTAL_1,
		EINK_IMAGE_RANDOM
	}
}
